spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/order;LOCK_TIMEOUT=10000
    username: test
    password: test123
    hikari:
      maximum-pool-size: 300

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false

